- type: job
  id: GSDeckhand
  name: job-name-deckhand
  description: job-description-deckhand
  playTimeTracker: GSJobDeckhand
  startingGear: GSDeckhandGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Common
  - Maintenance

- type: startingGear
  id: GSDeckhandGear
  equipment:
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSDeckhandChameleonOutfit
  job: GSDeckhand
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterCargo
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesFingerless
