# Overall play time is in the upstream file.
# Jobs. Sorted by department because alphabetically annoys me.

# Cargo
- type: playTimeTracker
  id: GSJobDeckhand

- type: playTimeTracker
  id: GSJobQuartermaster

# Command
- type: playTimeTracker
  id: GSJobSkipper

- type: playTimeTracker
  id: GSJobFirstOfficer

# Engineering
- type: playTimeTracker
  id: GSJobMachinist

- type: playTimeTracker
  id: GSJobMasterMachinist

- type: playTimeTracker
  id: GSJobBoatswain

#Medical
- type: playTimeTracker
  id: GSJobApothecary

- type: playTimeTracker
  id: GSJobMasterSurgeon

- type: playTimeTracker
  id: GSJobSurgeon

# Security
- type: playTimeTracker
  id: GSJobDetective

- type: playTimeTracker
  id: GSJobMasteratArms

# Service
- type: playTimeTracker
  id: GSJobHerbalist

- type: playTimeTracker
  id: GSJobClown

- type: playTimeTracker
  id: GSJobMime

- type: playTimeTracker
  id: GSJobMariner

- type: playTimeTracker
  id: GSJobSteward
