# Overall play time is in the upstream file.
# Jobs. Sorted by department because alphabetically annoys me.

# Cargo
- type: playTimeTracker
  id: GSJobDeckhand

- type: playTimeTracker
  id: GSJobQuartermaster

# Command
- type: playTimeTracker
  id: GSJobSkipper

- type: playTimeTracker
  id: GSJobFirstOfficer

# Engineering
- type: playTimeTracker
  id: GSJobAtmosphericTechnician

- type: playTimeTracker
  id: GSJobChiefEngineer

- type: playTimeTracker
  id: GSJobStationEngineer

#Medical
- type: playTimeTracker
  id: GSJobChemist

- type: playTimeTracker
  id: GSJobChiefMedicalOfficer

- type: playTimeTracker
  id: GSJobMedicalDoctor

# Security
- type: playTimeTracker
  id: GSJobDetective

- type: playTimeTracker
  id: GSJobHeadOfSecurity

# Service
- type: playTimeTracker
  id: GSJobBotanist

- type: playTimeTracker
  id: GSJobClown

- type: playTimeTracker
  id: GSJobMime

- type: playTimeTracker
  id: GSJobPassenger

- type: playTimeTracker
  id: GSJobServiceWorker
