- type: job
  id: GSApothecary
  name: job-name-apothecary
  description: job-description-apothecary
  playTimeTracker: GSJobApothecary
  requirements:
    - !type:DepartmentTimeRequirement
      department: GSMedical
      time: 5h
  startingGear: GSApothecaryGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-ms
  access:
  - Common
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: GSApothecaryGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetMedical

- type: chameleonOutfit
  id: GSApothecaryChameleonOutfit
  job: GSApothecary
  equipment:
    head: ClothingHeadHatBeretMedic
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabChem
    gloves: ClothingHandsGlovesLatex
