- type: job
  id: GSMasterSurgeon
  name: job-name-ms
  description: job-description-ms
  playTimeTracker: GSJobMasterSurgeon
  requirements:
    - !type:RoleTimeRequirement
      role: GSJobApothecary
      time: 2.5h
    - !type:RoleTimeRequirement
      role: GSJobSurgeon
      time: 5h
    - !type:DepartmentTimeRequirement
      department: GSMedical
      time: 10h
  weight: 10
  startingGear: GSMasterSurgeonGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-first-officer
  canBeAntag: false
  access:
  - Medical
  - Command
  - Common
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: GSMasterSurgeonGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: GSMasterSurgeonChameleonOutfit
  job: GSMasterSurgeon
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
