- type: job
  id: GSSurgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: GSJobSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: GSMedical
      time: 2.5h
  startingGear: GSSurgeonGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-ms
  access:
  - Common
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: GSSurgeonGear
  equipment:
    ears: ClothingHeadsetMedical

- type: chameleonOutfit
  id: GSSurgeonChameleonOutfit
  job: GSSurgeon
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
