- type: job
  id: GSPassenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: GSJobPassenger
  startingGear: GSPassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: GSPassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSPassengerChameleonOutfit
  job: GSPassenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
