- type: job
  id: GSBotanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: GSJobBotanist
  startingGear: GSBotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FourTwenty
    prototype: CannabisSeeds

- type: startingGear
  id: GSBotanistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltPlantFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSBotanistChameleonOutfit
  job: GSBotanist
  equipment:
    head: ClothingHeadBandBotany
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterApronBotanist
    gloves: ClothingHandsGlovesLeather
