- type: job
  id: GSClown
  name: job-name-clown
  description: job-description-clown
  playTimeTracker: GSJobClown
  startingGear: GSClownGear
  icon: "JobIconClown"
  supervisors: job-supervisors-qm
  access:
  - Common
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random values. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
          Heat: 3
      catchingFailDamage:
        types:
          Blunt: 1
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: GSClownGear
  equipment:
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder
    id: ClownPDA
    ears: ClothingHeadsetService
  inhand:
  - FoolboxFilled
  storage:
    back:
    - RubberStampClown
    - CrayonRainbow

- type: chameleonOutfit
  id: GSClownChameleonOutfit
  job: GSClown
  equipment:
    head: ClothingHeadHatXmasCrown
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingHeadHatFlowerWreath
    outerClothing: ClothingOuterClownPriest
    gloves: ClothingHandsGlovesColorYellowBudget
