- type: job
  id: GSHerbalist
  name: job-name-herbalist
  description: job-description-herbalist
  playTimeTracker: GSJobHerbalist
  startingGear: GSHerbalistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-qm
  access:
  - Common
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FourTwenty
    prototype: CannabisSeeds

- type: startingGear
  id: GSHerbalistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltPlantFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSHerbalistChameleonOutfit
  job: GSHerbalist
  equipment:
    head: ClothingHeadBandBotany
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterApronBotanist
    gloves: ClothingHandsGlovesLeather
