- type: job
  id: GSJanitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: GSJobJanitor
  startingGear: GSJanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  access:
  - Common
  - Service
  - Janitor
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: GSJanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  #storage:
    #back:
    #- Stuff

- type: startingGear
  id: GSJanitorMaidGear #terrible.
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled

- type: chameleonOutfit
  id: GSJanitorChameleonOutfit
  job: GSJanitor
  equipment:
    head: ClothingHeadHatPurplesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterWinterJani
    gloves: ClothingHandsGlovesJanitor
