- type: job
  id: GSMariner
  name: job-name-mariner
  description: job-description-mariner
  playTimeTracker: GSJobMariner
  startingGear: GSMarinerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Common
  - Maintenance

- type: startingGear
  id: GSMarinerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSMarinerChameleonOutfit
  job: GSMariner
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
