- type: job
  id: GSMime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: GSJobMime
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 4h
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-qm
  access:
  - Common
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers
      preventWriting: true
    - type: FrenchAccent

- type: startingGear
  id: GSMimeGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    id: MimePDA
    pocket1: CrayonMime
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: chameleonOutfit
  id: GSMimeChameleonOutfit
  job: GSMime
  equipment:
    head: ClothingHeadHatMimesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingNeckScarfStripedZebra
    outerClothing: ClothingOuterWinterMime
