- type: job
  id: GSServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: GSJobServiceWorker
  requirements:
  - !type:DepartmentTimeRequirement
    department: GSService
    time: 0.5h
  startingGear: GSServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  access:
  - Common
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics

- type: startingGear
  id: GSServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSServiceWorkerChameleonOutfit
  job: GSServiceWorker
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterVest
    gloves: ClothingHandsGlovesColorBlack
