- type: job
  id: GSSteward
  name: job-name-steward
  description: job-description-steward
  playTimeTracker: GSJobSteward
  requirements:
  - !type:DepartmentTimeRequirement
    department: GSService
    time: 0.5h
  startingGear: GSStewardGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-qm
  access:
  - Common
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics

- type: startingGear
  id: GSStewardGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSStewardChameleonOutfit
  job: GSSteward
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterVest
    gloves: ClothingHandsGlovesColorBlack
