- type: job
  id: GSBoatswain
  name: job-name-boatswain
  description: job-description-boatswain
  playTimeTracker: GSJobBoatswain
  requirements:
    - !type:DepartmentTimeRequirement
      department: GSEngineering
      time: 2.5h
  startingGear: GSBoatswainGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-mm
  access:
  - Common
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics

- type: startingGear
  id: GSBoatswainGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSBoatswainChameleonOutfit
  job: GSBoatswain
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
