- type: job
  id: GSMachinist
  name: job-name-machinist
  description: job-description-machinist
  playTimeTracker: GSJobMachinist
  requirements:
  - !type:DepartmentTimeRequirement
    department: GSEngineering
    time: 2.5h
  startingGear: GSMachinistGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Common
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe

- type: startingGear
  id: GSMachinistGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSMachinistChameleonOutfit
  job: GSMachinist
  equipment:
    head: ClothingHeadHelmetAtmosFire
    mask: ClothingMaskGasAtmos
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterSuitAtmosFire
    gloves: ClothingHandsGlovesColorYellow
