- type: job
  id: GSTechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: GSJobTechnicalAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1h
    - !type:DepartmentTimeRequirement
      department: GSEngineering
      time: 10h
      inverted: true # stop playing intern if you're good at engineering!
  startingGear: GSTechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Common
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: GSTechnicalAssistantGear
  equipment:
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    pocket2: BookEngineersHandbook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: GSTechnicalAssistantChameleonOutfit
  job: GSTechnicalAssistant
  equipment:
    head: ClothingHeadHatHardhatOrange
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterVestHazard
    gloves: ClothingHandsGlovesColorYellow
