- type: job
  id: GSHeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: GSJobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: GSJobDetective
      time: 5h # knowing how to use the tools is important
    - !type:DepartmentTimeRequirement
      department: GSSecurity
      time: 10h
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Common
  - Brig
  - Security
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: GSHoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: GSHeadOfSecurityChameleonOutfit
  job: GSHeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
