- type: job
  id: GSMasteratArms
  name: job-name-maa
  description: job-description-maa
  playTimeTracker: GSJobMasteratArms
  requirements:
    - !type:DepartmentTimeRequirement
      department: GSSecurity
      time: 10h
  weight: 10
  startingGear: GSMasteratArmsGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-skipper
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Common
  - Brig
  - Security
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: GSMasteratArmsGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: GSMasteratArmChameleonOutfit
  job: GSMasteratArms
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
