- type: job
  id: GSSecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: GSJobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10h
    - !type:DepartmentTimeRequirement
      department: GSSecurity
      time: 10h
      inverted: true # stop playing intern if you're good at security!
  startingGear: GSSecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: GSSecurityCadetGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: BookSecurity
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: GSSecurityCadetChameleonOutfit
  job: GSSecurityCadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetBasic
    eyes: ClothingEyesHudSecurity
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckScarfStripedRed
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesColorBlack
