- type: department
  id: GSCargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - GSDeckhand
  - GSQuartermaster

- type: department
  id: GSService
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - GSClown
  - GSMariner
  - GSMime
  - GSQuartermaster
  - GSSteward

- type: department
  id: GSCommand
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - GSFirstOfficer
  - GSMasteratArms
  - GSSkipper
  primary: false
  weight: 100

- type: department
  id: GSEngineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - GSBoatswain
  - GSMachinist
  - GSMasterMachinist

- type: department
  id: GSMedical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - GSApothecary
  - GSMasterSurgeon
  - GSSurgeon

- type: department
  id: GSSecurity
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - GSDetective
  - GSMasteratArms
