name: Build & Test Debug

on:
  push:
    branches: [ master, stable ]
  merge_group:
  pull_request:
    types: [ review_requested ]
    branches: [ master, stable ]

jobs:
  build:
    if: github.actor != 'GSBot' && github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Master
      uses: GreenShiftStation/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Pull engine updates
      uses: GreenShiftStation/submodule-dependency@c236e9954c5e8e0034d7d0ba16fbba23494ba557

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: GreenShiftStation/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25
      with:
        dotnet-version: 10.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration DebugOpt --no-restore /m

    - name: Run Content.Tests
      run: dotnet test --no-build --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0

    - name: Run Content.IntegrationTests
      shell: pwsh
      run: |
        $env:DOTNET_gcServer=1
        dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed
  ci-success:
    name: GreenShift Build & Test Debug
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
